## Numpy

In [1]:
import numpy as np

### Basic exercises

####  Ceate a 1D array of numbers from 0 to 9

In [2]:
# Solution
np.array([1,2,3])

array([1, 2, 3])

#### Create a 3×3 numpy array of all True’s

In [ ]:
# Solution
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Replace all odd numbers in arr with -1

In [ ]:
# Input
arr = np.arange(10)
print(arr)
# Solution
for i in arr:
  if arr[i] % 2 != 0:
    arr[i] = -1

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Convert a 1D array to a 2D array with 2 rows

In [3]:
# Input
arr = np.arange(10)
print(arr)

# Solution
np.reshape(arr, (2, -1))

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Stack arrays a and b vertically and then horizontally

In [9]:
# Input
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# Solution
hstack = np.concatenate([a, b], axis=1)
hstack1 = np.hstack([a,b])
print(hstack)
print(hstack1)
vstack = np.concatenate([a, b], axis=0)
vstack1 = np.vstack([a, b])
print(vstack)
print(vstack1)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### Find positions where elements of a and b match

In [10]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
result = np.where(a == b)
print(result)

(array([1, 3, 5, 7]),)


####  Get all items between 5 and 10 from a

In [12]:
# Input
a = np.arange(15)

# Solutions
result = np.where((a >= 5) & (a <= 10))
print(result)

result1 = [(a >= 5) & (a <= 10)]
print(result1)


(array([ 5,  6,  7,  8,  9, 10]),)
[array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True, False, False, False, False])]


#### Get the positions of top 5 maximum values in a given array a

In [14]:
# Input
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)

# Solution:
result = a.argsort()[-5:][::-1]
print(result)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[15 10  3  7 18]


#### Compute the min-by-max (i.e. min/max) for each row for given 2d numpy array (see [apply_along_axis](https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html#numpy-apply-along-axis))

In [16]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Solution
max = np.amax(a, axis=1)
print(max)
min = np.amin(a, axis=1)
print(min)
result = max / min
print(result)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
[4 1 3 3 1]
[2.25 8.   2.   1.   9.  ]


####  Find the duplicate entries in the given numpy array and mark them as True. First time occurrences should be False.

In [23]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

# Solution
result = np.full(a.shape, True)
unique = np.unique(a, return_index=True)[1]
result[unique] = False
print(result)

Array:  [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


#### Find the index of 5th repetition of number 1 in x
Make use of numpy.where

In [28]:
# Input
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
# Soluzione
result = np.where(x == 1)[0]
print(result[n-1])

8


#### Compute the moving average of window size 3, for the given 1D array
Make use of numpy.convolve

In [30]:
# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

# Solution
result  = np.convolve(arr, np.ones((3,))/3, mode='valid')
print(result)

[6.33333333 6.         5.66666667 4.66666667 3.66666667 2.
 3.66666667 3.        ]


### Iris dataset

#### Import the iris dataset from iris.txt
See np.genfromtxt, load the dataset with dtype=np.str

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [38]:
# Input filepath
FILEPATH = "/content/drive/MyDrive/lab/data/iris.txt"
# Soultion
iris = np.genfromtxt(FILEPATH, delimiter=',', dtype= str)
print(iris)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

#### Print the unique labels of the dataset

In [39]:
# Solution
result =  np.unique(iris[:, 4])
print(result)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


#### Find how many samples (i.e. rows) we have for each unique label

In [40]:
# Solution
result = np.unique(iris[:, 4], return_counts=True)
print(result)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([50, 50, 50]))


#### Find the mean, median, standard deviation of iris's sepallength (1st column)
See np.genfromtxt, load only the 1st column with the appropiate data type

In [47]:
# Solution
sepallength  =  np.genfromtxt(FILEPATH, delimiter=',', dtype= float, usecols=[0])


mean_val = np.mean(sepallength)
print("mean: ", mean_val)
median_val = np.median(sepallength)
print("median: ", median_val)
std_val = np.std(sepallength)
print("std: ", std_val)


mean:  5.843333333333334
median:  5.8
std:  0.8253012917851409


####  Find the mean, median, standard deviation of iris's sepallength (1st column) for each unique labels

In [53]:
# Solution
iris_data = np.genfromtxt(FILEPATH, delimiter=',', dtype=None, encoding='utf-8')

lengths = np.array([row[0] for row in iris_data])
species = np.array([row[4] for row in iris_data])


unique_species = np.unique(species)



for s in unique_species:
    mask = (species == s)

    s_lengths = lengths[mask]

    print(f"{s:<16} mean: {np.mean(s_lengths):.2f} | median: {np.median(s_lengths):.2f} | std: {np.std(s_lengths):.2f}")



Iris-setosa      mean: 5.01 | median: 5.00 | std: 0.35
Iris-versicolor  mean: 5.94 | median: 5.90 | std: 0.51
Iris-virginica   mean: 6.59 | median: 6.50 | std: 0.63


####  Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3

In [61]:
# Solution
sepal_length = iris[:, 0].astype(float)
petal_length = iris[:, 2].astype(float)

volume = (np.pi * petal_length * (sepal_length ** 2)) / 3

iris_with_volume = np.column_stack((iris, volume))

print(iris_with_volume[:2])

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa' '38.13265162927291']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa' '35.200498485922445']]


#### Randomly sample iris's species such that setosa is twice the number of versicolor and virginica
See [numpy.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html#numpy-random-choice)

In [66]:
probs = np.where(species == 'Iris-setosa', 0.5/50, 0.25/50)

np.random.seed(100)
sample_indices = np.random.choice(len(species), size=20, p=probs)
sampled_species = species[sample_indices]

print(sampled_species)


['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa']


#### Sort the iris dataset based on sepallength column

In [68]:
# Solution
sepallength_indices = np.argsort(iris[:, 0].astype(float))
iris_sorted = iris[sepallength_indices]
print(iris_sorted[:10])

[['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '3.0' '1.3' '0.2' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['4.6' '3.2' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']]


#### Find the most frequent value of petal length (3rd column) in iris dataset

In [72]:
# Solution
petal_length = iris[:, 2].astype(float)
unique_values, counts = np.unique(petal_length, return_counts=True)
most_frequent_value = unique_values[np.argmax(counts)]
print(most_frequent_value)

1.5


#### Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

see [np.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html#numpy-argwhere)

In [73]:
# Solution
petalwidth = iris[:, 3].astype(float)
result = np.argwhere(petalwidth > 1.0)[0]
print(result)

[50]


#### Get the rows having petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [79]:
# Solution
condition1 = petal_length > 1.5
# print(condition1)
condition2 = sepal_length < 5.0
# print(condition2)

mask = condition1 & condition2

print(iris[mask])

[['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['4.9' '2.5' '4.5' '1.7' 'Iris-virginica']]
